apiVersion: apps/v1
kind: Deployment
metadata:
  name: dental-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dental-backend
  template:
    metadata:
      labels:
        app: dental-backend
    spec:
      containers:
        - name: dental-backend
          image: paultrunc/dental-backend:latest
          ports:
            - containerPort: 5000
          env:
            - name: PORT
              value: "5000"
